"use strict";
module.exports = {
    label: 'BACNet-Device',
    id: 'bacnet',
    autoDiscoveryDeviceTypes: [],
    devices: [
        {
            plugin: 'bacnet/bacNetDevice',
            class: 'Controller',
            id: 'bd-controller',
            label: 'BD Controller',
            sensors: [],
            services: [],
            configuration: {
                simulated: false,
            },
            actors: [
            {
                id: 'bi1',
                label: 'Binary Input Actor 1',
                type: 'binaryInput',
                logLevel: 'debug',
                configuration: {
                    objectId: 0,
                },
            },
            {
                id: 'bv1',
                label: 'Binary Value Actor 1',
                type: 'binaryValue',
                logLevel: 'debug',
                configuration: {
                    objectId: 0,
                },
            },
            {
                id: 'bl1',
                label: 'Binary Light Actor 1',
                type: 'binaryLight',
                logLevel: 'debug',
                configuration: {
                    lightActiveObjectId: 9,
                    lightActiveObjectType: `BinaryValue`,
                },
            },
            {
                id: 'ai1',
                label: 'Analog Input Actor 1',
                type: 'analogInput',
                logLevel: 'debug',
                configuration: {
                    objectId: 0,
                },
            },
            {
                id: 'av1',
                label: 'Analog Value Actor 1',
                type: 'analogValue',
                logLevel: 'debug',
                configuration: {
                    objectId: 0,
                },
            },
            {
                id: 'msv1',
                label: 'Multi State Value Actor 1',
                type: 'multiStateValue',
                logLevel: 'debug',
                configuration: {
                    objectId: 0,
                },
            },
            {
                id: 'msi1',
                label: 'Multi State Input Actor 1',
                type: 'multiStateInput',
                logLevel: 'debug',
                configuration: {
                    objectId: 0,
                },
            },
            {
                id: 'la1',
                label: 'Light Actor 1',
                type: 'light',
                logLevel: 'debug',
                configuration: {
                    'levelFeedbackObjectId': 43,
                    'levelFeedbackObjectType': 'AnalogValue',
                    'levelModificationObjectId': 38,
                    'levelModificationObjectType': 'AnalogValue',
                    'lightActiveFeedbackObjectId': 15,
                    'lightActiveFeedbackObjectType': 'MultiStateValue',
                    'lightActiveModificationObjectId': 14,
                    'lightActiveModificationObjectType': 'MultiStateValue',
                    'lightActiveModificationValueOn': 2,
                    'lightActiveModificationValueOff': 1,
                },
            },
            {
                id: 'thermostat1',
                label: 'Thermostat',
                type: 'thermostat',
                logLevel: 'debug',
                configuration: {
                    'setpointFeedbackObjectId': 20,
                    'setpointFeedbackObjectType': 'AnalogValue',
                    'setpointModificationObjectId': 32,
                    'setpointModificationObjectType': 'AnalogValue',
                    'temperatureObjectId': 24,
                    'temperatureObjectType': 'AnalogValue',
                    'modeObjectId': 3,
                    'modeObjectType': 'MultiStateValue',
                },
            },
            {
                id: 'roomControl1',
                label: 'Room Control',
                type: 'roomControl',
                logLevel: 'debug',
                configuration: {
                    'setpointFeedbackObjectId': 20,
                    'setpointFeedbackObjectType': 'AnalogValue',
                    'setpointModificationObjectId': 32,
                    'setpointModificationObjectType': 'AnalogValue',
                    'temperatureObjectId': 24,
                    'temperatureObjectType': 'AnalogValue',
                },
            },
            {
                id: 'jalousie1',
                label: 'Jalousie',
                type: 'jalousie',
                logLevel: 'debug',
                configuration: {
                    'positionFeedbackObjectId': 20,
                    'positionFeedbackObjectType': 'AnalogValue',
                    'positionModificationObjectId': 32,
                    'positionModificationObjectType': 'AnalogValue',
                    'positionStepSize': 10,
                    'rotationFeedbackObjectId': 24,
                    'rotationFeedbackObjectType': 'AnalogValue',
                    'rotationModificationObjectId': 43,
                    'rotationModificationObjectType': 'AnalogValue',
                    'rotationUpValue': 0,
                    'rotationDownValue': 90,
                    'rotationStepSize': 15,
                    'actionObjectId': 14,
                    'actionObjectType': 'MultiStateValue',
                    'actionGoValue': 2,
                    'actionStopValue': 3
                },
            },
            {
                id: 'jalousieSimple1',
                label: 'Jalousie Simple',
                type: 'jalousieSimple',
                logLevel: 'debug',
                configuration: {
                    'motionDirectionObjectId': 0,
                    'motionDirectionObjectType': 'BinaryValue',
                    'stopValueObjectId': 9,
                    'stopValueObjectType': 'BinaryValue',
                    'stepDuration': 5,
                },
            },
            ],
        },
    ],
    services: [],
    eventProcessors: [],
    groups: [],
    jobs: [],
    data: [],
};
