export = {
    label: 'Disruptive-Technologies',
    id: 'dtplugin',
    autoDiscoveryDeviceTypes: [],
    devices: [
        {
            plugin: 'bacnet/bacnet-device.controller',
            class: 'Controller',
            id: 'bd-controller',
            label: 'BD Controller',
            sensors: [],
            services: [],
            configuration: {
                simulated: false,
            },
            actors: [
                // {
                //     id: 'asdfg123',
                //     label: 'Binary Input Actor 1',
                //     type: 'binary-input.actor',
                //     logLevel: 'debug',
                //     configuration: {
                //         objectId: 0,
                //     },
                // },
                // {
                //     id: 'asdfg123',
                //     label: 'Binary Value Actor 1',
                //     type: 'binary-value.actor',
                //     logLevel: 'debug',
                //     configuration: {
                //         objectId: 0,
                //     },
                // },
                // {
                //     id: 'asdfg123',
                //     label: 'Binary Light Actor 1',
                //     type: 'binary-light.actor',
                //     logLevel: 'debug',
                //     configuration: {
                //         lightActiveObjectId: 9,
                //         lightActiveObjectType: `BinaryValue`,
                //     },
                // },
                // {
                //     id: 'asdfg123',
                //     label: 'Analog Input Actor 1',
                //     type: 'analog-input.actor',
                //     logLevel: 'debug',
                //     configuration: {
                //         objectId: 0,
                //     },
                // },
                // {
                //     id: 'asdfg123',
                //     label: 'Analog Value Actor 1',
                //     type: 'analog-value.actor',
                //     logLevel: 'debug',
                //     configuration: {
                //         objectId: 0,
                //     },
                // },
                // {
                //     id: 'asdfg123',
                //     label: 'Multi State Value Actor 1',
                //     type: 'multi-state-value.actor',
                //     logLevel: 'debug',
                //     configuration: {
                //         objectId: 0,
                //     },
                // },
                // {
                //     id: 'asdfg123',
                //     label: 'Multi State Input Actor 1',
                //     type: 'multi-state-input.actor',
                //     logLevel: 'debug',
                //     configuration: {
                //         objectId: 0,
                //     },
                // },
                // {
                //     id: 'asdfg123',
                //     label: 'Light Actor 1',
                //     type: 'light.actor',
                //     logLevel: 'debug',
                //     configuration: {
                //         'levelFeedbackObjectId': 43,
                //         'levelFeedbackObjectType': 'AnalogValue',
                //         'levelModificationObjectId': 38,
                //         'levelModificationObjectType': 'AnalogValue',
                //         'lightActiveFeedbackObjectId': 15,
                //         'lightActiveFeedbackObjectType': 'MultiStateValue',
                //         'lightActiveModificationObjectId': 14,
                //         'lightActiveModificationObjectType': 'MultiStateValue',
                //         'lightActiveModificationValueOn': 2,
                //         'lightActiveModificationValueOff': 1,
                //     },
                // },
                // {
                //     id: 'thermostat1',
                //     label: 'Thermostat',
                //     type: 'thermostat.actor',
                //     logLevel: 'debug',
                //     configuration: {
                //         'setpointFeedbackObjectId': 20,
                //         'setpointFeedbackObjectType': 'AnalogValue',
                //         'setpointModificationObjectId': 32,
                //         'setpointModificationObjectType': 'AnalogValue',
                //         'temperatureObjectId': 24,
                //         'temperatureObjectType': 'AnalogValue',
                //         'modeObjectId': 3,
                //         'modeObjectType': 'MultiStateValue',
                //     },
                // },
                // {
                //     id: 'roomControl1',
                //     label: 'Room Control',
                //     type: 'room-control.actor',
                //     logLevel: 'debug',
                //     configuration: {
                //         'setpointFeedbackObjectId': 20,
                //         'setpointFeedbackObjectType': 'AnalogValue',
                //         'setpointModificationObjectId': 32,
                //         'setpointModificationObjectType': 'AnalogValue',
                //         'temperatureObjectId': 24,
                //         'temperatureObjectType': 'AnalogValue',
                //     },
                // },
                // {
                //     id: 'jalousie1',
                //     label: 'Jalousie',
                //     type: 'jalousie.actor',
                //     logLevel: 'debug',
                //     configuration: {
                //         'positionFeedbackObjectId': 20,
                //         'positionFeedbackObjectType': 'AnalogValue',
                //         'positionModificationObjectId': 32,
                //         'positionModificationObjectType': 'AnalogValue',
                //         'positionStepSize': 10,
                //         'rotationFeedbackObjectId': 24,
                //         'rotationFeedbackObjectType': 'AnalogValue',
                //         'rotationModificationObjectId': 43,
                //         'rotationModificationObjectType': 'AnalogValue',
                //         'rotationUpValue': 0,
                //         'rotationDownValue': 90,
                //         'rotationStepSize': 15,
                //         'actionObjectId': 14,
                //         'actionObjectType': 'MultiStateValue',
                //         'actionGoValue': 2,
                //         'actionStopValue': 3
                //     },
                // },
                // {
                //     id: 'jalousieSimple1',
                //     label: 'Jalousie Simple',
                //     type: 'jalousie-simple.actor',
                //     logLevel: 'debug',
                //     configuration: {
                //         'motionDirectionObjectId': 0,
                //         'motionDirectionObjectType': 'BinaryValue',
                //         'stopValueObjectId': 9,
                //         'stopValueObjectType': 'BinaryValue',
                //         'stepDuration': 5,
                //     },
                // },
            ],
        },
    ],
    services: [],
    eventProcessors: [],
    groups: [],
    jobs: [],
    data: [],
};
